# Generated by Django 6.0.5 on 2026-05-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_project_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('session_start', 'Session Start'), ('session_end', 'Session End'), ('server_start', 'Server Start'), ('server_stop', 'Server Stop'), ('file_change', 'File Change')], max_length=20),
        ),
    ]
